### ISSUE TITLE
테스트 코드 작성

### ISSUE THREAD

**Issue by imdaxsz** [team-abcdedu/abcdedu-frontend#121]
## 📝 개요

구현한 UI 컴포넌트, 인증, 프로필, 커뮤니티 기능에 대해서 테스트 코드 작성

## ✅ TODO

- [x] 프로필
  - [x] 프로필 페이지 (조회)
  - [x] 비밀번호 변경
  - [x] 프로필 수정
- [ ] 커뮤니티
- [x] Pagination
- [x] 문의
   - [x] 관리자 문의 목록 조회
   - [x] 관리자 문의 상세 조회
   - [x] 문의 페이지/문의 모달
- [ ] 인증
   - [ ] 회원가입
   - [ ] 로그인
   - [ ] 비밀번호 재설정
   - [ ] 이메일 인증
   - [ ] AuthModal
   - [ ] 회원 탈퇴
