### ISSUE TITLE
Footer 수정

### ISSUE THREAD

**Issue by yjenis** [team-abcdedu/abcdedu-frontend#19]
## 📝 개요
Footer 추가로 수정해야 할 부분

## ✅ TODO

- [ ] 메인페이지와 이외 페이지별 다르게 보이는 부분 구현(대표, 주소, 연락처, 이메일 유무)
- [x] 이용약관 모달 구현
- [x] 개인정보처리방침 모달 구현

**Comment by yjenis** [comment]
디자인 변경으로 해당 이슈 삭제
