### ISSUE TITLE
sentry 모니터링 환경 구축 및 에러 로그 수집

### ISSUE THREAD

**Issue by imdaxsz** [team-abcdedu/abcdedu-frontend#191]
## 📝 개요

sentry 모니터링 환경 구축 및 에러 로그 수집

## ✅ TODO

- [x] vite preload 이벤트 핸들러 추가 https://ko.vitejs.dev/guide/build#load-error-handling
- [x] 로깅할 오류
   - [x] 500번대
   - [x] 일부 400번대, 네트워크 오류 등
   - [x] 프론트 런타임 오류
- [x] 환경 구축
- [x] ErrorBoundary 추가
- [x] slack 연결
