### ISSUE TITLE
Header 수정

### ISSUE THREAD

**Issue by PHJoon** [team-abcdedu/abcdedu-frontend#26]
## 📝 개요
Header 수정

## ✅ TODO

- [x] 디자인 수정
- [x] 모바일 메뉴 외부 or Link 클릭 시 사라지게
- [x] 모바일 버전 헤더 
- [x] 중복 key 수정
