### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by PHJoon** [team-abcdedu/abcdedu-frontend#260]
## ✅ TODO

- [x] 클래스 페이지 뷰 - 로직 분리
- [x] 관리자 클래스 페이지 뷰 - 로직 분리
- [x] 클래스 class-lecture, subClass-subLecture 변수명 통일
- [ ] 과제
- [ ] 설문
- [ ] 관리자 - 유저 관리
